### ISSUE TITLE
add support for HTTPS to the website and SPARQL-endpoint

### ISSUE THREAD

**Issue by waldenn** [alishiba14/WorldKG-Knowledge-Graph#1]
Hi,

Thanks for an interesting data project. It would be great to be able to use HTTPS when using the "worldkg.org/sparql" SPARQL-endpoint, as browsers are very strict these days (not allowing mixed http/https access when on a secure URL).

It should not be difficult to set up for the webserver: https://letsencrypt.org/getting-started/

When needed you can also proxy other application-services by their port through your HTTPS-enabled site.

This is eg. what I do for an Apache2 site config:

     <Location /app/myapp>
        ProxyPass http://127.0.0.1:8000
        ProxyPassReverse http://127.0.0.1:8000
     </Location>

This allows URLs  with "/app/myapp" to go through to a local service listening on port 8000.

Once that is done, I'll be able to create an integration for the SPARQL-endpoint with my https://conze.pt project.

**Comment by alishiba14** [comment]
Hello @waldenn, we have added the HTTPS support to the website now. Thank you for your suggestion.
